language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  - export DOCKER_TAG=$(cat docker_tag.txt)

script:
  - docker --version # print the version for logging
  ## Build
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  ## Tagging
  - docker tag udagram-reverseproxy daovietchungptithotmail/udagram-reverseproxy:$DOCKER_TAG
  - docker tag udagram-api-feed daovietchungptithotmail/udagram-api-feed:$DOCKER_TAG
  - docker tag udagram-api-user daovietchungptithotmail/udagram-api-user:$DOCKER_TAG
  - docker tag udagram-frontend daovietchungptithotmail/udagram-frontend:$DOCKER_TAG

after_success:
  ## Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push daovietchungptithotmail/udagram-reverseproxy:$DOCKER_TAG
  - docker push daovietchungptithotmail/udagram-api-feed:$DOCKER_TAG
  - docker push daovietchungptithotmail/udagram-api-user:$DOCKER_TAG
  - docker push daovietchungptithotmail/udagram-frontend:$DOCKER_TAG
